version: '3.2'

services:
  db:
    image: mysql/mysql-server:5.7
    volumes:
      - /mnt/sdd/zoneminder/mysql/data:/var/lib/mysql
      - /mnt/sdd/zoneminder/mysql/conf:/etc/mysql:ro
    environment:
     - TZ=Europe/Copenhagen
     - MYSQL_USER=zmuser
     - MYSQL_PASSWORD=zmpass
     - MYSQL_DATABASE=zm
     - MYSQL_ROOT_PASSWORD=mysqlpsswd
     - MYSQL_ROOT_HOST=%
     - ZM_TIMEZONE=Europe/Copenhagen
    networks:
     - zoneminder    
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

      placement:
        constraints:
          - node.labels.storage==yes

  web:
    depends_on:
      - db
    image: quantumobject/docker-zoneminder
    networks:
      - traefik-public
      - zoneminder
    ports:
      - "8081:80" #So I can access it on internal network on a shared host
    volumes:
      - /var/empty
      - /mnt/sdd/zoneminder/backups:/var/backups
      - /mnt/sdd/zoneminder/cache:/var/cache/zoneminder
      - type: tmpfs
        target: /dev/shm
    environment:
     - TZ=Europe/Copenhagen
     - ZM_DB_HOST=db
     - ZM_TIMEZONE=Europe/Copenhagen

    depends_on:
      - db
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

      placement:
        constraints:
          - node.labels.storage==yes
      replicas: 1
      labels:
        - traefik.enable=true
        - "traefik.http.routers.zm.rule=Host(`zm.${BASE_HOST}`)"
        - "traefik.http.routers.zm.entrypoints=websecure"
        - "traefik.http.routers.zm.tls.certresolver=le"
#        - "traefik.http.routers.zm.middlewares=addzm"
        - "traefik.http.services.zm.loadbalancer.server.port=80"
        - "traefik.http.services.zm.loadbalancer.server.scheme=http"
        - "traefik.http.middlewares.auth.basicauth.users=${USER_ZONEMINDER}"
        - "traefik.http.middlewares.addzm.addprefix.prefix=/zm"

networks:
  traefik-public:
    external: true
  zoneminder:
  